### PR TITLE
NWPS-300: Multi organisation logo implementation

### PR DESCRIPTION
**Pull request by smanivasag**
- A new DocumentType `Logo` has been introduced to content manage logos (Image and its associated link).
- A new DocumentType `LogoGroup` to group `Logo` documents together so as to reuse it.
- A new field `Logo group` has been added to all existing DocumentTypes (e.g. `hee:landingPage`, `hee:listingPage`, etc). This approach of adding `LogoGroup` document directly to the page document rather than through a catalog (component) is expected to greatly reduce/avoid migration effort when we move to experience pages (to avoid migrating catalog document to page document). Note that `Logo group` field is not added to `News` DocumentType (`NWPS-796`) yet as the PR https://github.com/Manifesto-Digital/hee-cms-platform/pull/152 is not merged with `master` yet.
- A new catalog `Multi org logo` has been introduced to include multi org logos to the header of channel pages. This catalog takes the same page document (e.g. documents of `hee:landingPage`, `hee:listingPage`, etc) that the main container section takes.
- All existing prototype pages (e.g. `blog-page`, `contentpage`, `minihub-page`, etc) have been updated to add the `Multi org logo` container to the header section of the page.
- `/hst:hee/hst:configurations/common/hst:abstractpages/base/header/parent-link` component (responsible for rendering `Part of NHS Health Education England (opens in a new window)` link in the header) and its associated template, resource bundle labels, etc have been removed as the section is now removed from the new header design.
- ChannelInfo class `uk.nhs.hee.web.channels.WebsiteInfo` has been updated to take both `Org name & descriptor` and the parameter names have been refactored for consistency.
- An updater script `BuildMultiOrgLogoContainerItemComponentForWorkspacePages` has been created to build `header/top/multi-org-logo/multi-org-logo` ContainerItemComponent (`hst:containeritemcomponent`) for existing workspace pages based on its existing main container document so that multi org logo would render automatically for existing pages when Editor associates LogoGroup document to the main container document (e.g. `hee:landingPage`, `hee:listingPage`, etc documents). Look up updater script execution log for any warnings of nodes to apply the changes `header/top/multi-org-logo/multi-org-logo` manually.

**Notes & next steps:**
- All mini-hub child pages i.e. mini-hub standard content pages will use the mini-hub header rather than the individual child standard content page headers (as mini-hub child pages are essentially sharing mini-hub page header).
- Add `Logo group` field to `News` (`hee:news`) DocumentType when the PR https://github.com/Manifesto-Digital/hee-cms-platform/pull/152 is merged with master.
- Support for `Multi org logo` on `hee:AfterForm` DocumentType is yet to be added. DocumentType `hee:AfterForm` seems to be lacking many meta fields that the other DocumentTypes has and so a separate ticket needs to be added in the backlog to keep this DocumentType up to date and add `Multi org logo` support.
- When completed running `BuildMultiOrgLogoContainerItemComponentForWorkspacePages` updater script, make sure to look up for any warnings of nodes that needs adding `header/top/multi-org-logo/multi-org-logo` ContainerItemComponent manually.
- UK FPO logo support isn't added yet and it will be dealt separately as Eleanor indicated in the ticket description.
- Integrate further commits/fixes that comes from https://github.com/Manifesto-Digital/hee-prototypes/pull/47 FE PR based on the review comments.
- Currently `header/top/multi-org-logo` container is duplicated across all prototype pages (e.g. `blog-page`, `contentpage`, `minihub-page`, etc) and a thread https://community.bloomreach.com/t/options-to-create-reusable-page-containers-for-prototype-pages/2933 has been raised on bloomreach community to see if the container could be centralised.

**Manual steps:**
- ChannelInfo settings/parameters (e.g. `/hst:hee/hst:configurations/lks/hst:workspace/hst:channel/hst:channelinfo`) for all our existing channels (`lks, dental, digital-transformation & medical`) should be updated to reflect the following changes in all brCloud env:
  - `organizationName` should be renamed as `organisationDescriptor`.
  - `GTMContainerID ` should be renamed as `gtmContainerId`.
- Run `BuildMultiOrgLogoContainerItemComponentForWorkspacePages` updater script to add `multi-org-logo` container and container item with main container document. Make sure to look up for any warnings post execution and apply the `multi-org-logo` container & container item manually.

Thanks!

### CODE REVIEW

**Review by Raq-HEE — APPROVED** [review]
Hi @smanivasag @adaMiclos - This is looking good. I've tested locally and it looks fine to me.

**Comment by smanivasag** [comment]
Hi @adaMiclos - Could you merge the PR, deploy onto dev & staging and test ? thanks

**Comment by smanivasag** [comment]
> Hi @adaMiclos - Could you merge the PR, deploy onto dev & staging and test ? thanks

@Raq-HEE @adaMiclos - Sorry, I am currently making a quick change to `Logo` DocumentType to choose the Logo type (rather than choosing the Image image). Will make a commit soon...

@adaMiclos - Please do not merge the PR yet. Thanks!

**Comment by smanivasag** [comment]
Hi @Raq-HEE @adaMiclos - Have made a commit 4228052cd023182e627aa04b5e9ac844d87fab9e to support rendering logos based on the chosen Logo type (rather than letting Editors to manage logo images within CMS) for consistency. Could you review ? thanks

**Comment by smanivasag** [comment]
Hi @adaMiclos - Thanks for 4a3bc4a99d35f3f648c57292347f846602a99068 commit and it looks good. Made another commit 9bf923518b676d6e81801fdcf4643966f01ab057 on top of it to move `<span>` tag around the conditions. Thanks!

**Comment by smanivasag** [comment]
Hi @Raq-HEE - Could you review the latest commits 4228052cd023182e627aa04b5e9ac844d87fab9e, 4a3bc4a99d35f3f648c57292347f846602a99068 and 9bf923518b676d6e81801fdcf4643966f01ab057 ? thanks

**Comment by Raq-HEE** [comment]
> Hi @Raq-HEE - Could you review the latest commits [4228052](https://github.com/Manifesto-Digital/hee-cms-platform/commit/4228052cd023182e627aa04b5e9ac844d87fab9e), [4a3bc4a](https://github.com/Manifesto-Digital/hee-cms-platform/commit/4a3bc4a99d35f3f648c57292347f846602a99068) and [9bf9235](https://github.com/Manifesto-Digital/hee-cms-platform/commit/9bf923518b676d6e81801fdcf4643966f01ab057) ? thanks

These look good @Selva

**Review by Raq-HEE — APPROVED** [review]
Hi @smanivasag - Commits [4228052](https://github.com/Manifesto-Digital/hee-cms-platform/commit/4228052cd023182e627aa04b5e9ac844d87fab9e), [4a3bc4a](https://github.com/Manifesto-Digital/hee-cms-platform/commit/4a3bc4a99d35f3f648c57292347f846602a99068) and [9bf9235](https://github.com/Manifesto-Digital/hee-cms-platform/commit/9bf923518b676d6e81801fdcf4643966f01ab057) look good. Approved.

**Pull request merged**
