### PR TITLE
HEE-311, HEE-317 & HEE-169: Navigation Map Implementation, Search Box fixes for Mobile and Dropdown Menu Integration

### PR DESCRIPTION
**Pull request by smanivasag**
- HEE-311: Navigation Map (Content Block) Implementation (for Home page).
- HEE-317: Integration of search box fixes for mobile.
- HEE-169: Integration of Dropdown Menus.
  - Top Navs containing Sub Navs, but no-link will be skipped i.e. it wouldn't be rendered as the first link item in the dropdown menu.
  - Top Navs with no Sub Navs as well as no-links will be rendered with `#` to keep the visitor on the same page. Editors/WebMasters should be advised accordingly in order to avoid this scenario.
  - Sub Navs with no-links will be rendered with `#` to keep the visitor on the same page, but `no-link` CSS class would be added to them to indicate that it is not a link. Editors/WebMasters should be advised accordingly in order to avoid this scenario.

The above tickets are grouped together as they all involve updating CSS and JS files and to avoid merge conflicts.

Note that the PR also includes the fix for `HEE-319: Navigation Map region hover links to incorrect URL`.

Thank you!

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @Raq-HEE - The PR is now ready for review, thanks

**Comment by Raq-HEE** [comment]
> HEE-311: Navigation Map (Content Block) Implementation (for Home page).

Not sure if agreed with design team, but the layout looks different to the figma designs

image

- there isn't a white background in the figma design 
- the links appear on the left in figma
- there's a lot more spacing on the list of links links compared to figma
- a summary text field is missing

**Comment by Raq-HEE** [comment]
> HEE-311: Navigation Map (Content Block) Implementation (for Home page).

The solution with the drop downs indicating the type of map, and subsequent drop downs for the regions may not be the easiest thing to author. Although the custom validation helps with ensuring data integrity, it may be worth exploring other options. I'll tag Will in the ticket to find out how often this is likely to be used. If it's just once, then the authoting effort could be justfied as is.

Ideally, it would be nice to add some conditional logic on the map type selector, that displays all the nested fieldsets assicated with the particular map types. But don't think it's behaviour we can easily or elegantly customise.

The alternative we could potentially consider, is having a seperate content type for each of the map types, with the regions pre added as defaults. With that, it'd add bloat to the content blocks lists. Not, sure if it's possible to add a nested content blocks region for Navigation Map.

Happy to approve as is, but interested in your thoughts on the points, so can discuss offline.

**Comment by Raq-HEE** [comment]
>     * HEE-317: Integration of search box fixes for mobile.

Am being picky here, so feel free to ignore. Around the 631px  browser width the menu and search misa-align with logo. So tweak of the media query breakpoint. Happy to pass as is, but thought I'd mention incase there are any devices that use that width.
image

**Comment by Raq-HEE** [comment]
> HEE-169: Integration of Dropdown Menus.

Again another minor one. It appears that non synchronsied mouse down, mouse up and mouse click events, css focus, active can create undesired behaviour. 
image

**Review by Raq-HEE — COMMENTED** [review]
Hi @smanivasag @goodvibes , I've added some comments, which are minor, and unlikely to be spotted during 'normal' site visitor behaviour on the search and the menu.

I've also added some food for thought on approach on content structures and whether we ought to consider alternatives.

Otherwise, it looks really good, and can approve if you're happy with it as it.

**Comment by smanivasag** [comment]
> > HEE-311: Navigation Map (Content Block) Implementation (for Home page).
> 
> Not sure if agreed with design team, but the layout looks different to the figma designs
> 
> image
> 
> * there isn't a white background in the figma design
> * the links appear on the left in figma
> * there's a lot more spacing on the list of links links compared to figma
> * a summary text field is missing

@goodvibes - Could you take a look at the above FE design issues ? Thanks!

**Comment by smanivasag** [comment]
> > HEE-311: Navigation Map (Content Block) Implementation (for Home page).
> 
> The solution with the drop downs indicating the type of map, and subsequent drop downs for the regions may not be the easiest thing to author. Although the custom validation helps with ensuring data integrity, it may be worth exploring other options. I'll tag Will in the ticket to find out how often this is likely to be used. If it's just once, then the authoting effort could be justfied as is.
> 
> Ideally, it would be nice to add some conditional logic on the map type selector, that displays all the nested fieldsets assicated with the particular map types. But don't think it's behaviour we can easily or elegantly customise.
> 
> The alternative we could potentially consider, is having a seperate content type for each of the map types, with the regions pre added as defaults. With that, it'd add bloat to the content blocks lists. Not, sure if it's possible to add a nested content blocks region for Navigation Map.
> 
> Happy to approve as is, but interested in your thoughts on the points, so can discuss offline.

@Raq-HEE - Thanks for the thoughts on this. As discussed during standup, the ideal solution is something hard to implement based on the current field types and config offered by brXM OOTB. One thing we can do is to add all region fieldsets for all Map Type (as couldn't see any option to expand only fieldsets for the chosen Map Type) and suggest authors to remove the ones that are relevant, but this is going to bloat the content form which might worsen authoring experience.

Alternatively, we can separate out region fieldsets as a separate DocumentType (as you mentioned), but it might be a overkill again as the maps are expected to be used on the channel Home pages only and also expected not to change frequently.

I guess the solution we have in place is little compromised and optimised after researching through other options. We can probably give Will a demo on this (as you mentioned) to get his initial thoughts and take it forward from there. Thanks!

**Comment by smanivasag** [comment]
> > ```
> > * HEE-317: Integration of search box fixes for mobile.
> > ```
> 
> Am being picky here, so feel free to ignore. Around the 631px, browser width the menu and search mis-align with logo. So tweak of the media query breakpoint. Happy to pass as is, but thought I'd mention incase there are any devices that use that width.
> image

@goodvibes - Could you take a look at this ? Thanks!

**Comment by smanivasag** [comment]
> > HEE-169: Integration of Dropdown Menus.
> 
> Again another minor one. It appears that non synchronsied mouse down, mouse up and mouse click events, css focus, active can create undesired behaviour.
> image

@goodvibes - Could you take a look at this ? Thanks!

**Comment by goodvibes** [comment]
Nav-Map component has been updated

**Comment by goodvibes** [comment]
Menu button / search box no longer break @ 641px (shortened tablet search bar)

**Comment by goodvibes** [comment]
@Raq-HEE Could you clarify exactly what you were doing to make the drop-down menu's behave badly please?

**Comment by Raq-HEE** [comment]
> 
> 
> @Raq-HEE Could you clarify exactly what you were doing to make the drop-down menu's behave badly please?

Pressing the mouse down, and dragging it away whilsts pressed down, and releasing the mouse press outside of the menu item area.

**Comment by smanivasag** [comment]
Hi @goodvibes - Have integrated FE PRs https://github.com/Manifesto-Digital/hee-prototypes/pull/29, https://github.com/Manifesto-Digital/hee-prototypes/pull/30 and https://github.com/Manifesto-Digital/hee-prototypes/pull/31 and have observed that `dist/js/main.min.js` requires `/js/components/map.js` & `/js/components/submenu.js` which I guess supposed to be resolved and embedded within `dist/js/main.min.js`. Otherwise, I think we will end up with minifying component specific js files and integrate them onto platform which may not be what we wanted. Moreover, it might affect performance of the pages due to too many network calls (to pull component specific js files). Could you look into this ?

Apart from this, have observed the following:
- Navigation Map
  - We might need to get rid of left padding on navigation map content in order to be aligned with design.
  - The spacing between the links seems to be inconsistent between map types (dental vs higher vs medical).
    Screenshot 2021-09-10 at 08 06 48
  - There is a lot of space between title and links.
- Dropdown menu
  - The focus seems to be changing when clicking on the dropdown menu i.e. the top menu gets a yellow focus for a moment when clicking and then looses it.

@goodvibes @Raq-HEE - In order to avoid blocking the PR to be reviewed, have embedded `/js/components/map.js` & `/js/components/submenu.js` component classes back in `app/assets/javascript/main.js` for now (meanwhile you look into embedding component classes within `dist/js/main.min.js`), created the bundle and integrated. This PR is now ready for review. Thanks!

**Comment by Raq-HEE** [comment]
Hi @goodvibes - I didn't spot this on the prototype app, but 

> Dropdown menu
> 
>     * The focus seems to be changing when clicking on the dropdown menu i.e. the top menu gets a yellow focus for a moment when clicking and then looses it.

@goodvibes , I initially didn't spot this on the prototype, but was able to replicate this on Firefox. Will approve so that it can go into staging, but just a heads up that this will at some point need to be fixed on the front end.

**Comment by Raq-HEE** [comment]
@smanivasag , @goodvibes - thanks for applying these fixes. As discussed in last weeks dev/design meet, will approve to go into staging where we can get wider team feedback.

**Comment by Raq-HEE** [comment]
@smanivasag happy for you to merge and deploy through to staging.

**Pull request merged**
