### PR TITLE
HEE-164: Change the navigation items to match IA 4.1

### PR DESCRIPTION
**Pull request by thojava**

### CODE REVIEW

**Review by smanivasag — COMMENTED** [review]
Could we add a Content Action (https://documentation.bloomreach.com/14/library/concepts/configuration-management/manage-content.html) [hcm-actions.yaml] in order to clean up the existing SiteMenuItems (that are no longer required) from local/brCloud dev environments ?

**Comment by smanivasag** [comment]
@MattBrooksManifesto @duncanheron Fyi - We have placed these SiteMenuItems under `repository-data/site-development` (as these are env specific configurations and we wouldn't want to manage/override them on brCloud higher env) and so these would be deployed to local and brCloud development environments only.

For Test, Staging and Prod brCloud env - These SiteMenuItems needs to be created and managed by us initially and then eventually by HEE Authors. Thanks!

**Comment by thojava** [comment]
@smanivasag Your point of adding remove action is nice which can help repository under local and brCloud being clean up automatically by the bootstrap. But It seem Bloomreach have limit or error when putting action on `site-development` module.
We have PathNotFoundException on the file org.onehippo.cm.engine.ConfigurationBaselineService line 1112. 
From what I read from the code then it only supports on modules `development` and `application`

**Comment by smanivasag** [comment]
Ah Ok, thanks for checking @thojava. I reckon it's because part of `/hst:hst/hst:configurations/lks/hst:workspace` sits between site and site-development modules and so the bootstrap mechanism couldn't identify it as content.

Could we use `Groovy Updater Script` to automate these cleanups going forward in case if manually fixing them on local & brCloud isn't an option ?

Ref. https://documentation.bloomreach.com/14/library/concepts/update/update-hst-configuration.html#scroll_reloading-updated-hst-workspace-content and https://developers.bloomreach.com/blog/2020/creating-automated-scripts-to-update-the-workspace.html

**Review by duncanheron — APPROVED** [review]

**Review by duncanheron — APPROVED** [review]
It would be nice to find a way to clean up - but it might be worth adding a new ticket so we arent blocked on a small navigation change

**Review by smanivasag — APPROVED** [review]

**Pull request merged**
