### PR TITLE
HEE-95: Search result page

### PR DESCRIPTION
**Pull request by thojava**
- Implement the search result page on the foundation of the bulletin page. The search result page can be access from http://localhost:8080/site/search/results or http://localhost:8080/site/search or calling from the search box in the top header.
- Installed URLRewriter plugin and setup redirection from /search to /search/results
- I have not implemented the Date filter yet because we do not have the design for that

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @thojava - Thanks for the PR and it looks great. Could you check on the following ?

- Looks like some bottom padding is required between filter tags and the first search result item.
- The pagination seems to be not providing option to go back to the previous search results page. Or is it designed this way for any reason(s) ?
- Looks like the document type search filters (Guidance, LandingPage) are currently seem to have been controlled in the component class `uk.nhs.hee.web.components.SearchResultsComponent`. If possible, could we try and use `Document Types` field of `listingPage` DocumentType ?

Thank you!

**Comment by duncanheron** [comment]
>     * The pagination seems to be not providing option to go back to the previous search results page. Or is it designed this way for any reason(s) ?

> 
> 
> Thank you!

I can successfully use both the Next and previous links - is this what you meant @smanivasag ?

@thojava if I select both filters `guidence` and `landingpage` then click next in the pagination - one of the filters is lost.

**Comment by duncanheron** [comment]
@thojava thanks - how much effort would it be to keep the filter box expanded if options are selected? I think it adds alot of value for the user.

**Comment by smanivasag** [comment]
> > ```
> > * The pagination seems to be not providing option to go back to the previous search results page. Or is it designed this way for any reason(s) ?
> > ```
> 
> > Thank you!
> 
> I can successfully use both the Next and previous links - is this what you meant @smanivasag ?
> 
> @thojava if I select both filters `guidence` and `landingpage` then click next in the pagination - one of the filters is lost.

@duncanheron  - Yes, the previous link is not displaying on my side at least. Not sure if I am missing something here.

**Comment by thojava** [comment]
> @thojava thanks - how much effort would it be to keep the filter box expanded if options are selected? I think it adds alot of value for the user.

@duncanheron That is related to javascript thing which I have investigated in detail yet but I expect that can be 4 hours. Should I add new ticket to handle that ?

**Comment by thojava** [comment]
@smanivasag I have performance some enhancement. Could you review ?

**Comment by duncanheron** [comment]
@thojava if I select both filters guidence and landing page then click next in the pagination - one of the filters is lost.
I also notice if you click previous and next the url params keep adding and end up with this in the url `http://localhost:8080/site/search/results?page=1&amp;amp;amp;amp;pageSize=2&amp;amp;amp;pageSize=2&amp;amp;pageSize=2&amp;pageSize=2`

**Comment by thojava** [comment]
@duncanheron Yes I has been able to fixed the issue. That was related to the directive 
`<#ftl output_format="HTML">`

**Comment by duncanheron** [comment]
> @duncanheron Yes I has been able to fixed the issue. That was related to the directive
> `<#ftl output_format="HTML">`

@thojava Pagination seems much better thanks. 🎉 

Last thing I am seeing some warnings on my local - could you check if you are also seeing these and if they are directly caused by this PR? 
```
[WARNING] [talledLocalContainer] %d{HH:mm:ss} WARN  [HstFreemarkerServlet] The following has evaluated to null or missing:
[INFO] [talledLocalContainer]   text=Home
[INFO] [talledLocalContainer] ==> breadcrumbLink.text  [in template "webfile:/freemarker/hee/layout/base-breadcrumb.ftl" at line 14, column 90]
[INFO] [talledLocalContainer]   url=/site/
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] ], uk.nhs.hee.web.components.beans.BreadcrumbLink@135094ee[
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer]   text=<null>
[INFO] [talledLocalContainer]   url=/site/search
[INFO] [talledLocalContainer] ]]
[INFO] [talledLocalContainer] Tip: It's the step after the last dot that caused this error, not those before it.
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] FTL stack trace ("~" means nesting-related):
[INFO] [talledLocalContainer]   - Failed at: ${breadcrumbLink.text}  [in template "webfile:/freemarker/hee/layout/base-breadcrumb.ftl" at line 14, column 88]
[INFO] [talledLocalContainer] ----. To see the stack trace, set 'org.hippoecm.hst.servlet.HstFreemarkerServlet' log-level to debug in log4j configuration or runtime via the logging servlet
[WARNING] [talledLocalContainer] %d{HH:mm:ss} WARN  [HstFreemarkerServlet] The following has evaluated to null or missing:
[INFO] [talledLocalContainer] ==> parentBreadcrumbLink.text  [in template "webfile:/freemarker/hee/layout/base-breadcrumb.ftl" at line 22, column 132]
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] Tip: It's the step after the last dot that caused this error, not those before it.
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] FTL stack trace ("~" means nesting-related):
[INFO] [talledLocalContainer]   - Failed at: ${parentBreadcrumbLink.text}  [in template "webfile:/freemarker/hee/layout/base-breadcrumb.ftl" at line 22, column 130]
[INFO] [talledLocalContainer] ----. To see the stack trace, set 'org.hippoecm.hst.servlet.HstFreemarkerServlet' log-level to debug in log4j configuration or runtime via the logging servlet
```

**Comment by thojava** [comment]
@duncanheron that is related to breadcrumb building, I have just enhanced it.

@smanivasag Do you fell right with the solution of adding parameter name `excludedForBreadcumb" to the `hst:siteMapItem` and set it to be true when we do not want it to be available on the breadcrumb. Like the /search because /search always being redirect to /search/results

**Review by duncanheron — APPROVED** [review]

**Pull request merged**
